openapi: "3.0.2"
info:
  title: API User
  version: "1.0"
servers:
  - url: http://localhost:8080/{basePath}/{version}
    description: local dev url
    variables:
      basePath:
        enum:
          - 'api'
        default: 'api'
      version:
        enum:
          - 'v1'
        default: 'v1'
tags:
  - name: User
    description: Operaciones relacionadas con usuarios.
paths:
  '/user':
    get:
      tags:
        - User
      summary: Obtener todos los usuarios
      operationId: getUsers
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /user/{userId}:
    get:
      tags:
        - User
      summary: Obtener usuario por ID
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: NOT FOUND
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Identificador único del usuario
        name:
          type: string
          description: Nombre del usuario
        address:
          type: string
          description: Dirección del usuario
        age:
          type: integer
          description: Edad del usuario
        phone:
          type: string
          description: Número de teléfono del usuario
        email:
          type: string
          description: Correo electrónico del usuario
        password:
          type: string
          description: Contraseña del usuario
          format: password
        role:
          type: string
          description: Rol del usuario
        status:
          type: string
          description: Estado del usuario