version: "3.8"
services:
  db:
    image: postgres:17
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: postgresqlAppContainer
    container_name: postgresqlAppContainer
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: APP
    ports:
      - "5432:5432"
    volumes:
      - postgresqlAppVolume:/var/lib/postgresql
      - postgresql_dataAppVolume:/var/lib/postgresql/data

volumes:
  postgresqlAppVolume:
  postgresql_dataAppVolume:
